language: generic

install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.12.18/terraform_0.12.18_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
# - mkdir ~/bin
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"
    script: terraform version
 

Terraform_Init:
  - provider: script
    skip_cleanup: true
    script: terraform init 
    on:
      branch: master
